// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusinessOrganizationInfo = "business_organization_info"

// BusinessOrganizationInfo mapped from table <business_organization_info>
type BusinessOrganizationInfo struct {
	ID                  string    `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	PersonaID           string    `gorm:"column:persona_id;not null" json:"persona_id"`
	VerifiedStatus      string    `gorm:"column:verified_status;default:pending" json:"verified_status"`
	RegistrationNumber  string    `gorm:"column:registration_number" json:"registration_number"`
	Name                string    `gorm:"column:name" json:"name"`
	Address             string    `gorm:"column:address" json:"address"`
	LegalForm           string    `gorm:"column:legal_form" json:"legal_form"`
	RegistrationCountry string    `gorm:"column:registration_country" json:"registration_country"`
	Industry            string    `gorm:"column:industry" json:"industry"`
	FoundingDate        time.Time `gorm:"column:founding_date" json:"founding_date"`
	CreatedAt           time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;not null" json:"updated_at"` 
	BusinessOrganizationRegionInfo *BusinessOrganizationRegionInfo `gorm:"foreignKey:OrganizationInfoID;references:ID" json:"business_organization_region_info,omitempty"`
}

// TableName BusinessOrganizationInfo's table name
func (*BusinessOrganizationInfo) TableName() string {
	return TableNameBusinessOrganizationInfo
}
