// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusinessOrganizationRegionInfo = "business_organization_region_info"

// BusinessOrganizationRegionInfo mapped from table <business_organization_region_info>
type BusinessOrganizationRegionInfo struct {
	ID                       string                   `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	OrganizationInfoID       string                   `gorm:"column:organization_info_id;not null" json:"organization_info_id"`
	CountryCode              string                   `gorm:"column:country_code;not null" json:"country_code"`
	RegionSpecificData       string                   `gorm:"column:region_specific_data;not null" json:"region_specific_data"`
	CreatedAt                time.Time                `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt                time.Time                `gorm:"column:updated_at;not null" json:"updated_at"` 
}

// TableName BusinessOrganizationRegionInfo's table name
func (*BusinessOrganizationRegionInfo) TableName() string {
	return TableNameBusinessOrganizationRegionInfo
}
