// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBusinessIndividualInfo = "business_individual_info"

// BusinessIndividualInfo mapped from table <business_individual_info>
type BusinessIndividualInfo struct {
	ID           string    `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	PersonaID    string    `gorm:"column:persona_id;not null" json:"persona_id"`
	PersonalData string    `gorm:"column:personal_data" json:"personal_data"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Persona      Persona   `gorm:"foreignKey:persona_id;references:id" json:"persona"`
}

// TableName BusinessIndividualInfo's table name
func (*BusinessIndividualInfo) TableName() string {
	return TableNameBusinessIndividualInfo
}
