// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        string    `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	AuthorID  string    `gorm:"column:author_id;not null" json:"author_id"`
	PostID    string    `gorm:"column:post_id;not null" json:"post_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	Author    Persona   `gorm:"foreignKey:author_id;references:id" json:"author"`
	Post      Post      `gorm:"foreignKey:post_id;references:id" json:"post"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
