// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/lib/pq"
)

const TableNamePersonaProfile = "persona_profile"

// PersonaProfile mapped from table <persona_profile>
type PersonaProfile struct {
	ID               string         `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	PersonaID        string         `gorm:"column:persona_id;not null;unique" json:"persona_id"`
	DisplayName      string         `gorm:"column:display_name;not null" json:"display_name"`
	ProfileImageURL  *string        `gorm:"column:profile_image_url" json:"profile_image_url,omitempty"`
	Description      *string        `gorm:"column:description" json:"description,omitempty"`
	Email            string         `gorm:"column:email" json:"email,omitempty"`
	EmailShown       bool           `gorm:"column:email_shown;default:true" json:"email_shown,omitempty"`
	PhoneNumber      string         `gorm:"column:phone_number" json:"phone_number,omitempty"`
	PhoneNumberShown bool           `gorm:"column:phone_number_shown;default:true" json:"phone_number_shown,omitempty"`
	Website          string         `gorm:"column:website" json:"website,omitempty"`
	Tags             pq.StringArray `gorm:"type:text[];column:tags" json:"tags"`
	CreatedAt        time.Time      `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`

	// 🔗 관계 설정: PersonaBackgroundMedia와 일대다 관계
	BackgroundMedia []PersonaBackgroundMedia `gorm:"foreignKey:PersonaProfileID;references:ID" json:"background_media,omitempty"`
}

// TableName PersonaProfile's table name
func (*PersonaProfile) TableName() string {
	return TableNamePersonaProfile
}

// func (*PersonaProfile) BeforeCreate() error {
// 	return nil
// }
