// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePersona = "persona"

// Persona mapped from table <persona>
type Persona struct {
	ID           string       `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	Did          string       `gorm:"column:did;not null" json:"did"`
	PersonaType  PersonaType  `gorm:"column:persona_type;not null;default:personal" json:"persona_type"`
	BusinessType BusinessType `gorm:"column:business_type;default:null" json:"business_type,omitempty"`
	CreatedAt    *time.Time   `gorm:"column:created_at;not null;autoCreateTime:milli" json:"created_at"`
	UpdatedAt    *time.Time   `gorm:"column:updated_at;not null;autoUpdateTime:milli" json:"updated_at"`

	Profile                  *PersonaProfile           `gorm:"foreignKey:PersonaID;references:ID" json:"profile,omitempty"`
	BusinessOrganizationInfo *BusinessOrganizationInfo `gorm:"foreignKey:PersonaID;references:ID" json:"business_organization_info,omitempty"`
	BusinessIndividualInfo   *BusinessIndividualInfo   `gorm:"foreignKey:PersonaID;references:ID" json:"business_individual_info,omitempty"`
	MemberOf                 []PersonaMember           `gorm:"foreignKey:MemberPersonaID;references:ID" json:"member_of,omitempty"`
	Members                  []PersonaMember           `gorm:"foreignKey:PersonaID;references:ID" json:"members,omitempty"`
	OwnedPosts               []Post                    `gorm:"foreignKey:AuthorID;references:ID" json:"owned_posts,omitempty"`
	AuthoredPosts            []Post                    `gorm:"foreignKey:AuthorID;references:ID" json:"authored_posts,omitempty"`
	Comments                 []Comment                 `gorm:"foreignKey:AuthorID;references:ID" json:"comments,omitempty"`
	Subscribes               []PersonaSubscriber       `gorm:"foreignKey:SubscriberID;references:ID" json:"subscriptions,omitempty"`
	Subscribers              []PersonaSubscriber       `gorm:"foreignKey:PersonaID;references:ID" json:"subscribers,omitempty"`
}

// TableName Persona's table name
func (*Persona) TableName() string {
	return TableNamePersona
}
