// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePersonaMember = "persona_member"

// PersonaMember mapped from table <persona_member>
type PersonaMember struct {
	ID              string    `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	PersonaID       string    `gorm:"index;column:persona_id;not null" json:"persona_id"`
	MemberPersonaID string    `gorm:"index;column:member_persona_id;not null" json:"member_persona_id"`
	Role            string    `gorm:"column:role;not null;default:member" json:"role"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
    Persona         Persona   `gorm:"foreignKey:ID;references:PersonaID" json:"persona,omitempty"`
    MemberPersona   Persona   `gorm:"foreignKey:ID;references:MemberPersonaID" json:"member_persona,omitempty"`
}

// TableName PersonaMember's table name
func (*PersonaMember) TableName() string {
	return TableNamePersonaMember
}
