// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	// "github.com/lib/pq"
)

const TableNamePersonaBackgroundMedia = "persona_background_media"

// PersonaBackgroundMedia mapped from table <persona_background_media>
type PersonaBackgroundMedia struct {
	ID               string    `gorm:"column:id;primaryKey;type:text;default:uuid_generate_v4()" json:"id"`
	PersonaProfileID string    `gorm:"column:persona_profile_id;not null;index" json:"persona_profile_id"`
	MediaURL         string    `gorm:"column:media_url;not null" json:"media_url"`
	LinkedURL        *string    `gorm:"column:linked_url" json:"linked_url,omitempty"`
	ExpireDate       *time.Time `gorm:"column:expire_date" json:"expire_date,omitempty"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`
}


// TableName Post's table name
func (*PersonaBackgroundMedia) TableName() string {
	return TableNamePersonaBackgroundMedia
}
