// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWallet = "wallet"

// Wallet 모델
type Wallet struct {
	Did                string    `gorm:"column:did;primaryKey;type:text;default:uuid_generate_v4()" json:"did"`
	Email              string    `gorm:"column:email;type:text;not null;unique" json:"email"`
	MembershipType     string    `gorm:"column:membership_type;type:membership_type;not null;default:'free'" json:"membership_type"`
	CreatedAt          time.Time `gorm:"column:created_at;not null;autoCreateTime:milli" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;not null;autoUpdateTime:milli" json:"updated_at"`
	RegistrationSource string    `gorm:"column:registration_source;type:registration_source;not null;default:'mobile_app'" json:"registration_source"`

	// Wallet이 삭제될 경우 Persona들도 함께 삭제됨
	Personas []Persona `gorm:"foreignKey:Did;references:Did;constraint:OnUpdate:CASCADE,OnDelete:CASCADE" json:"personas"`
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
